# Generated by Django 2.2.20 on 2022-05-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20220520_1711'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='recipeingredientamount',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='unigue_ingredient_for_recipe'),
        ),
    ]
