# Generated by Django 2.2.20 on 2022-05-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20220520_1712'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='recipeingredientamount',
            constraint=models.CheckConstraint(check=models.Q(amount__gt=0), name='amount_gt_zero'),
        ),
    ]
