# Generated by Django 2.2.20 on 2022-05-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_userfavoriterecipe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfavoriterecipe',
            options={'verbose_name': 'Любимый рецепт', 'verbose_name_plural': 'Любимые рецепты'},
        ),
        migrations.AddConstraint(
            model_name='userfavoriterecipe',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unigue_recipe_user_favorite'),
        ),
    ]
