# Generated by Django 2.2.20 on 2022-05-31 16:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20220523_1325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usershoppingcart',
            options={'verbose_name': 'Покупка', 'verbose_name_plural': 'Покупки'},
        ),
        migrations.RemoveConstraint(
            model_name='recipe',
            name='cooking_time_gt_zero',
        ),
        migrations.RemoveConstraint(
            model_name='recipeingredientamount',
            name='amount_gt_zero',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(help_text='Время приготовления (в минутах)', validators=[django.core.validators.MinValueValidator(limit_value=1)], verbose_name='Время приготовления (в минутах)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='recipes/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='recipeingredientamount',
            name='amount',
            field=models.IntegerField(help_text='Количество', validators=[django.core.validators.MinValueValidator(limit_value=1)], verbose_name='Количество'),
        ),
    ]
