# Generated by Django 2.2.20 on 2022-05-23 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220523_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribeuser',
            name='author',
            field=models.ForeignKey(help_text='Автор, на которого подписаны', on_delete=django.db.models.deletion.CASCADE, related_name='subscribe', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
