# Generated by Django 2.2.20 on 2022-05-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Название', max_length=200, unique=True, verbose_name='Название'),
        ),
    ]
