# Generated by Django 2.2.20 on 2022-05-16 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Наименование', max_length=200, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Размерность',
                'verbose_name_plural': 'Размерности',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Имя игридиента', max_length=200, unique=True, verbose_name='Имя ингридиента')),
                ('measurement_unit', models.ForeignKey(help_text='Размерность', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='ingredients.MeasurementUnit', verbose_name='Размерность')),
            ],
            options={
                'verbose_name': 'Ингридиент',
                'verbose_name_plural': 'Ингридиенты',
                'ordering': ('name',),
            },
        ),
    ]
