name: Foodgram-app workflow

on: [push]

jobs:
  tests:
    services:
      postgres:
        image: postgres:10
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_user_123
        options:
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pep8-naming flake8-broken-line flake8-return
          pip install -r ./backend/foodgram_project/requirements.txt
      
      - name: Test with flake8
        run: |
          cd backend/foodgram_project/
          python -m flake8
      
      - name: Test with unittest
        env:
          DB_ENGINE: django.db.backends.postgresql
          DB_NAME: test_db
          DB_HOST: 127.0.0.1
          DB_PORT: 5432
          DB_PASS: test_user_123
          DB_USER: test_user
          SECRET_KEY: 5dc554e7-eaf4-42b9-9536-796687ec3019
        run: |
          cd backend/foodgram_project/
          python manage.py test
  send_message_test:
    runs-on: ubuntu-latest
    needs: tests
    steps:
    - name: send message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TG_TO }}
        token: ${{ secrets.TG_TOKEN }}
        message: ${{ github.workflow }} для ветви ${{ github.ref }} тесты пройдены! 
  build_and_push_to_docker_hub:
    if: ${{ github.ref == 'refs/heads/master' }}
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: backend/foodgram_project
          push: true
          tags: lorpaxx/foodgram_backend
  send_message_build_and_push:
    runs-on: ubuntu-latest
    needs: build_and_push_to_docker_hub
    steps:
    - name: send message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TG_TO }}
        token: ${{ secrets.TG_TOKEN }}
        message: ${{ github.workflow }} образ собран и отправелен на DockerHub! 
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push_to_docker_hub
    steps:
    - name: executing remote ssh commands to deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_IP }}
        username: ${{ secrets.HOST_USER }}
        key: ${{ secrets.HOST_SSH_KEY }}
        passphrase: ${{ secrets.HOST_PASSPHRASE }}
        script: |
          cd foodgram-project-react
          cd infra
          sudo docker-compose stop
          sudo docker-compose rm web
          sudo docker image rm lorpaxx/foodgram_backend
          rm .env
          touch .env
          echo POSTGRES_DB=${{ secrets.POSTGRES_DB }} >> .env
          echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env
          echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
          echo DEBUG=${{ secrets.DEBUG }} >> .env
          echo DB_ENGINE=${{ secrets.DB_ENGINE }} >> .env
          echo DB_NAME=${{ secrets.DB_NAME }} >> .env
          echo DB_USER=${{ secrets.DB_USER }} >> .env
          echo DB_PASS=${{ secrets.DB_PASS }} >> .env
          echo DB_HOST=${{ secrets.DB_HOST }} >> .env
          echo DB_PORT=${{ secrets.DB_PORT }} >> .env
          echo SECRET_KEY=${{ secrets.SECRET_KEY }} >> .env
          echo ALLOWED_HOST=${{ secrets.HOST_IP }} >> .env
          sudo docker-compose up -d
  send_message:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
    - name: send message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TG_TO }}
        token: ${{ secrets.TG_TOKEN }}
        message: ${{ github.workflow }} отправка на боевой сервер выполнена! 
          