name: Foodgram-app workflow

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pep8-naming flake8-broken-line flake8-return
          pip install -r ./backend/foodgram_project/requirements.txt
      
      - name: Test with flake8
        run: |
          cd backend/foodgram_project/
          python -m flake8
      
      - name: Test with unittest
        run: |
          cd backend/foodgram_project/
          python manage.py test